version: '3'
services:
  mindcrunch:
    image: mindcrunch
    build:
      context: mindcrunch
    privileged: true
    ports:
      - ${PORT:-4000}:4000
  ryu:
    image: ryu
    build:
      context: ryu
    privileged: true
    ports:
      - ${PORT:-8080}:8080
  mininet:
    image: mininet
    build:
      context: mininet
    privileged: true
    environment:
      - CONTROLLER=${CONTROLLER:-ryu}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
